-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.CompactDisplay
  ( CompactDisplay(..)
  , toString
  ) where

import Prelude

data CompactDisplay = Short | Long

derive instance Eq CompactDisplay

toString :: CompactDisplay -> String
toString = case _ of
  Short -> "short"
  Long -> "long"
