-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.CurrencyDisplay
  ( CurrencyDisplay(..)
  , toString
  ) where

import Prelude

data CurrencyDisplay
  = Code
  | Symbol
  | NarrowSymbol
  | Name

derive instance Eq CurrencyDisplay

toString :: CurrencyDisplay -> String
toString = case _ of
  Code -> "code"
  Symbol -> "symbol"
  NarrowSymbol -> "narrowSymbol"
  Name -> "name"
