-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.Day (Day(..), toString) where

import Prelude

data Day = Numeric | TwoDigit

derive instance Eq Day

toString :: Day -> String
toString = case _ of
  Numeric -> "numeric"
  TwoDigit -> "2-digit"
