-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.DayPeriod
  ( DayPeriod(..)
  , toString
  ) where

import Prelude

data DayPeriod = Narrow | Short | Long

derive instance Eq DayPeriod

toString :: DayPeriod -> String
toString = case _ of
  Narrow -> "narrow"
  Short -> "short"
  Long -> "long"
