-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.Era (Era(..), toString) where

import Prelude

data Era = Narrow | Short | Long

derive instance Eq Era

toString :: Era -> String
toString = case _ of
  Narrow -> "narrow"
  Short -> "short"
  Long -> "long"
