-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.Fallback
  ( Fallback(..)
  , toString
  ) where

import Prelude

data Fallback = Code | None

derive instance Eq Fallback

toString :: Fallback -> String
toString = case _ of
  Code -> "code"
  None -> "none"
