-- *** DO NOT EDIT! ***
-- This module is generated by `just generate-options`

module JS.Intl.Options.Fallback
  ( Fallback(..)
  , fromString
  , toString
  ) where

import Prelude

import Data.Maybe (Maybe(..))

data Fallback = Code | None

derive instance Eq Fallback

toString :: Fallback -> String
toString = case _ of
  Code -> "code"
  None -> "none"

fromString :: String -> Maybe Fallback
fromString = case _ of
  "code" -> Just Code
  "none" -> Just None
  _ -> Nothing
