-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.FormatMatcher
  ( FormatMatcher(..)
  , toString
  ) where

import Prelude

data FormatMatcher = Basic | BestFit

derive instance Eq FormatMatcher

toString :: FormatMatcher -> String
toString = case _ of
  Basic -> "basic"
  BestFit -> "best fit"
