-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.Granularity
  ( Granularity(..)
  , toString
  ) where

import Prelude

data Granularity = Grapheme | Word | Sentence

derive instance Eq Granularity

toString :: Granularity -> String
toString = case _ of
  Grapheme -> "grapheme"
  Word -> "word"
  Sentence -> "sentence"
