-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.Hour (Hour(..), toString) where

import Prelude

data Hour = Numeric | TwoDigit

derive instance Eq Hour

toString :: Hour -> String
toString = case _ of
  Numeric -> "numeric"
  TwoDigit -> "2-digit"
