-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.HourCycle
  ( HourCycle(..)
  , toString
  ) where

import Prelude

data HourCycle = H11 | H12 | H23 | H24

derive instance Eq HourCycle

toString :: HourCycle -> String
toString = case _ of
  H11 -> "h11"
  H12 -> "h12"
  H23 -> "h23"
  H24 -> "h24"
