-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.Hour
  ( Hour(..)
  , fromString
  , toString
  ) where

import Prelude

import Data.Maybe (Maybe(..))

data Hour = Numeric | TwoDigit

derive instance Eq Hour

toString :: Hour -> String
toString = case _ of
  Numeric -> "numeric"
  TwoDigit -> "2-digit"

fromString :: String -> Maybe Hour
fromString = case _ of
  "numeric" -> Just Numeric
  "2-digit" -> Just TwoDigit
  _ -> Nothing
