-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.LanguageDisplay
  ( LanguageDisplay(..)
  , toString
  ) where

import Prelude

data LanguageDisplay = Dialect | Standard

derive instance Eq LanguageDisplay

toString :: LanguageDisplay -> String
toString = case _ of
  Dialect -> "dialect"
  Standard -> "standard"
