-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.ListFormatType
  ( ListFormatType(..)
  , toString
  ) where

import Prelude

data ListFormatType
  = Conjunction
  | Disjunction
  | Unit

derive instance Eq ListFormatType

toString :: ListFormatType -> String
toString = case _ of
  Conjunction -> "conjunction"
  Disjunction -> "disjunction"
  Unit -> "unit"
