-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.LocaleMatcher
  ( LocaleMatcher(..)
  , toString
  ) where

import Prelude

data LocaleMatcher = BestFit | Lookup

derive instance Eq LocaleMatcher

toString :: LocaleMatcher -> String
toString = case _ of
  BestFit -> "best fit"
  Lookup -> "lookup"
