-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.Minute
  ( Minute(..)
  , toString
  ) where

import Prelude

data Minute = Numeric | TwoDigit

derive instance Eq Minute

toString :: Minute -> String
toString = case _ of
  Numeric -> "numeric"
  TwoDigit -> "2-digit"
