-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.Month (Month(..), toString) where

import Prelude

data Month
  = Numeric
  | TwoDigit
  | Narrow
  | Short
  | Long

derive instance Eq Month

toString :: Month -> String
toString = case _ of
  Numeric -> "numeric"
  TwoDigit -> "2-digit"
  Narrow -> "narrow"
  Short -> "short"
  Long -> "long"
