-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.Notation
  ( Notation(..)
  , toString
  ) where

import Prelude

data Notation
  = Standard
  | Scientific
  | Engineering
  | Compact

derive instance Eq Notation

toString :: Notation -> String
toString = case _ of
  Standard -> "standard"
  Scientific -> "scientific"
  Engineering -> "engineering"
  Compact -> "compact"
