-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.NumberFormatStyle
  ( NumberFormatStyle(..)
  , toString
  ) where

import Prelude

data NumberFormatStyle
  = Decimal
  | Currency
  | Percent
  | Unit

derive instance Eq NumberFormatStyle

toString :: NumberFormatStyle -> String
toString = case _ of
  Decimal -> "decimal"
  Currency -> "currency"
  Percent -> "percent"
  Unit -> "unit"
