-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.Second
  ( Second(..)
  , toString
  ) where

import Prelude

data Second = Numeric | TwoDigit

derive instance Eq Second

toString :: Second -> String
toString = case _ of
  Numeric -> "numeric"
  TwoDigit -> "2-digit"
