-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.SignDisplay
  ( SignDisplay(..)
  , toString
  ) where

import Prelude

data SignDisplay
  = Auto
  | Always
  | Never
  | ExceptZero

derive instance Eq SignDisplay

toString :: SignDisplay -> String
toString = case _ of
  Auto -> "auto"
  Always -> "always"
  Never -> "never"
  ExceptZero -> "exceptZero"
