-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.Style (Style(..), toString) where

import Prelude

data Style = Narrow | Short | Long

derive instance Eq Style

toString :: Style -> String
toString = case _ of
  Narrow -> "narrow"
  Short -> "short"
  Long -> "long"
