-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.TimeStyle
  ( TimeStyle(..)
  , toString
  ) where

import Prelude

data TimeStyle = Full | Long | Medium | Short

derive instance Eq TimeStyle

toString :: TimeStyle -> String
toString = case _ of
  Full -> "full"
  Long -> "long"
  Medium -> "medium"
  Short -> "short"
