-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.UnitDisplay
  ( UnitDisplay(..)
  , toString
  ) where

import Prelude

data UnitDisplay = Narrow | Short | Long

derive instance Eq UnitDisplay

toString :: UnitDisplay -> String
toString = case _ of
  Narrow -> "narrow"
  Short -> "short"
  Long -> "long"
