-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.Usage (Usage(..), toString) where

import Prelude

data Usage = Sort | Search

derive instance Eq Usage

toString :: Usage -> String
toString = case _ of
  Sort -> "sort"
  Search -> "search"
