-- *** DO NOT EDIT! ***
-- This module is generated by `just generate-options`

module JS.Intl.Options.Usage
  ( Usage(..)
  , fromString
  , toString
  ) where

import Prelude

import Data.Maybe (Maybe(..))

data Usage = Sort | Search

derive instance Eq Usage

toString :: Usage -> String
toString = case _ of
  Sort -> "sort"
  Search -> "search"

fromString :: String -> Maybe Usage
fromString = case _ of
  "sort" -> Just Sort
  "search" -> Just Search
  _ -> Nothing
