-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.UseGrouping
  ( UseGrouping(..)
  , toString
  ) where

import Prelude

data UseGrouping = Min2 | Auto | Always

derive instance Eq UseGrouping

toString :: UseGrouping -> String
toString = case _ of
  Min2 -> "min2"
  Auto -> "auto"
  Always -> "always"
