-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.Weekday
  ( Weekday(..)
  , toString
  ) where

import Prelude

data Weekday = Narrow | Short | Long

derive instance Eq Weekday

toString :: Weekday -> String
toString = case _ of
  Narrow -> "narrow"
  Short -> "short"
  Long -> "long"
