-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.Year (Year(..), toString) where

import Prelude

data Year = Numeric | TwoDigit

derive instance Eq Year

toString :: Year -> String
toString = case _ of
  Numeric -> "numeric"
  TwoDigit -> "2-digit"
