-- *** DO NOT EDIT! ***
-- This module is generated by ./script/generate-options.sh

module JS.Intl.Options.Year
  ( Year(..)
  , fromString
  , toString
  ) where

import Prelude

import Data.Maybe (Maybe(..))

data Year = Numeric | TwoDigit

derive instance Eq Year

toString :: Year -> String
toString = case _ of
  Numeric -> "numeric"
  TwoDigit -> "2-digit"

fromString :: String -> Maybe Year
fromString = case _ of
  "numeric" -> Just Numeric
  "2-digit" -> Just TwoDigit
  _ -> Nothing
