name: CI

# Run CI when a PR is opened against the branch `main`
# and when one pushes a commit to `main`.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: "Nix check"
        run: nix flake check

      - name: "Run tests"
        run: |
          nix develop --command 'run-install'
          nix develop --command 'run-test'

      - name: "Check format"
        run: nix develop --command 'run-check-format'

